commercetools/commercetools-payone-integration

service/src/main/java/com/commercetools/pspadapter/payone/config/PayoneConfig.java
service/src/main/java/com/commercetools/pspadapter/payone/config/PropertyProvider.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/BaseRequest.java
service/src/test/java/com/commercetools/pspadapter/payone/config/PayoneConfigTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/BankTransferInAdvanceRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/CreditCardRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/PaypalRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/PostfinanceCardRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/SofortRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/SofortWithoutIbanRequestFactoryTest.java

@butenkor @mht-dotsource @ahalberkamp pls review:
fixed issue #122: added default encoding **`UTF_8`** to all Payone requests

Request encoding

---

build.gradle
service/src/main/java/com/commercetools/pspadapter/payone/IntegrationService.java
service/src/main/resources/log4j.properties

@butenkor @ahalberkamp 
i've fixed routes logs with the next changes:
- update `Spark` version to use the latest API
- root request **/** now redirected to **/health**
- raise log level of `MatcherFilter` to _warn_ to avoid logs of unmapped routes.

Cpi 125 fix route logs

---

functionaltests/src/test/java/specs/paymentmethods/sofortueberweisung/ChargeImmediatelyFixture.java
functionaltests/src/test/java/util/WebDriver3ds.java
functionaltests/src/test/java/util/WebDriverSofortueberweisung.java
functionaltests/src/test/java/util/constant/WebDriverCommon.java
functionaltests/src/test/java/util/constant/WebDriverSofortueberweisungConstants.java

This PR solves 2 problems in Sofortüberweisung tests:
- fixes the references according to new web page controls/input names (see [this](https://github.com/commercetools/commercetools-payone-integration/pull/180/files#diff-fb901a72f37294c99b6a07524e574e4cR8) and [this](https://github.com/commercetools/commercetools-payone-integration/pull/180/files#diff-9f9c9c48c18aee576acface9676dc372R30))
- wait for inputs to be enabled before clicking them, because they are enabled asynchronously when you change other inputs values (for example, _login_ button is enabled only when both name and tan are input). See [`ExpectedConditions.elementToBeClickable` usage](https://github.com/commercetools/commercetools-payone-integration/pull/180/files#diff-4887a49c8d02ab752b32e97b6c562762R57)
- run all 3 payment …

#176: fix sofortüberweisung integration tests

---

build.gradle
functionaltests/src/test/java/specs/response/HealthResponseFixture.java
functionaltests/src/test/resources/specs/response/HealthResponse.html
service/src/main/java/com/commercetools/Main.java
service/src/main/java/com/commercetools/pspadapter/payone/IntegrationService.java
service/src/main/java/com/commercetools/pspadapter/payone/ServiceFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/config/PropertyProvider.java
service/src/main/java/com/commercetools/pspadapter/payone/config/ServiceConfig.java
service/src/test/java/com/commercetools/pspadapter/payone/config/PropertyProviderTest.java
service/src/test/java/com/commercetools/pspadapter/payone/config/ServiceConfigTest.java

Update `/health` JSON response so it [contains now fields](https://github.com/commercetools/commercetools-payone-integration/pull/188/files#diff-a684bbe1ce55a8f4dea792d69dd8397aR156):
- `"status": 200` - legacy hardcoded value
- `"tenants": [...]` - [list of registered tenants name for this application](https://github.com/commercetools/commercetools-payone-integration/pull/188/files#diff-a684bbe1ce55a8f4dea792d69dd8397aR48)
- `"applicationInfo":{"version": "XXX", "title": "app-name"}` - [version and application name info](https://github.com/commercetools/commercetools-payone-integration/pull/188/files#diff-8405d481fb7e3e4ff137072c1e8384ecR59). The version and title are [built-in into jar](https://github.com/commercetools/commercetools-payone-integration/pull/188/files#diff-c197962302397baf …

176 health response

---

service/src/main/java/com/commercetools/pspadapter/payone/IntegrationService.java

Output health response as pretty-formatted JSON, if `pretty` URL query argument is specified.
This is useful for the developers when you have to review, for example, which tenants are registered in current service, or running application version, so instead of:
http://localhost:8080/health
```json
{"status":200,"tenants":["HEROKU_FIRST_TENANT","HEROKU_SECOND_TENANT"],"applicationInfo":{"version":"DEBUG-VERSION","title":"DEBUG-TITLE"}}
```
you have:
http://localhost:8080/health?pretty
```json
{
"status" : 200,
"tenants" : [ "HEROKU_FIRST_TENANT", "HEROKU_SECOND_TENANT" ],
"applicationInfo" : {
"version" : "DEBUG-VERSION",
"title" : "DEBUG-TITLE"
}
}```

Allow pretty print for /health URL

---

docs/Field-Mapping.md
service/src/main/java/com/commercetools/pspadapter/payone/notification/common/CaptureNotificationProcessor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/common/UnsupportedTransactionExecutor.java
service/src/test/java/com/commercetools/pspadapter/payone/notification/common/BaseChargedNotificationProcessorTest.java
service/src/test/java/com/commercetools/pspadapter/payone/notification/common/CaptureNotificationProcessorTest.java

addresses issue #209:
When notification `capture` is received from Payone, we have to set transaction state to `Success` instead of `Pending`, because `capture` means money transferred to the customer.
See [CaptureNotificationProcessor](https://github.com/commercetools/commercetools-payone-integration/pull/211/files#diff-7412916c8bd0808e0e616165c9cc3ed1) class.
Also, if there is no respective `Charge` transaction in the updated payment - [create such a transaction with `Success` state](https://github.com/commercetools/commercetools-payone-integration/pull/211/files#diff-7412916c8bd0808e0e616165c9cc3ed1R74)
[Updated respective tests](https://github.com/commercetools/commercetools-payone-integration/pull/211/files#diff-f0e35d699b64d57c15cf9ef518442b07L88) (only unit, because capture …

209 fix capture transaction status

---

functionaltests/src/test/java/specs/scheduler/ScheduledJobFixtureHelper.java
functionaltests/src/test/java/specs/scheduler/ScheduledJobShort2Fixture.java
functionaltests/src/test/java/specs/scheduler/ScheduledJobShortFixture.java
functionaltests/src/test/resources/specs/scheduler/ScheduledJobShort.html
functionaltests/src/test/resources/specs/scheduler/ScheduledJobShort2.html

Make the integration test of scheduled job more stable: [increase waiting timeout](https://github.com/commercetools/commercetools-payone-integration/pull/215/files#diff-7b0194e26c1b0d2b9f1082b0b773db8dR122) because scheduled jobs are sequential and thus may take longer then just 30 seconds to update 2 tenants in a row.
Partially fixes #205 (ScheduledJobShort2 fails very often because the payment is sill not APPROVED after waiting timeout, but later it becomes approved)

205 scheduled job test fix

---

build.gradle
service/src/main/java/com/commercetools/pspadapter/payone/PaymentDispatcher.java
service/src/main/java/com/commercetools/pspadapter/payone/ScheduledJob.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/ctp/paymentmethods/PaymentMethod.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/banktransfer/BankTransferRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/paymentinadvance/BankTransferInAdvanceRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/BankTransferWithoutIbanBicRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/BanktTransferInAdvanceRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/CreditCardRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/PayoneRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/PaypalRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/PostFinanceBanktransferRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/SofortBankTransferRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceAuthorizationTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceChargeTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BaseBankTransferInAdvanceTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
service/src/main/java/com/commercetools/util/function/TriFunction.java
service/src/test/java/com/commercetools/pspadapter/payone/PaymentDispatcherTest.java
service/src/test/java/com/commercetools/pspadapter/payone/domain/ctp/paymentmethods/PaymentMethodTest.java
service/src/test/java/com/commercetools/pspadapter/payone/domain/payone/model/banktransfer/BankTransferRequestTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/BankTransferInAdvanceRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/PostfinanceCardRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/PostfinanceEfinanceRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/SofortRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/SofortWithIbanRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/SofortWithoutIbanRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceChargeTransaction_attemptExecutionTest.java
service/src/test/java/com/commercetools/pspadapter/tenant/TenantFactoryTest.java

as a hot fix for https://github.com/commercetools/commercetools-payone-integration/issues/217:
Now we don't validate transaction type: the customer should create proper transaction type on theirs own, the service simply executes transaction on payone, if it is possible.
- [`PaymentMethods`](https://github.com/commercetools/commercetools-payone-integration/pull/218/files#diff-3439e6d93c20fc6f9d51971b99d0cd1e)
- removed `AUTHORIZATION`/`CHARGE` limits for every payment method
- define global `supportedTransactionTypes` set of supported types
- [`BankTransferAuthorizationRequest/BankTransferRequest `](https://github.com/commercetools/commercetools-payone-integration/pull/218/files#diff-c0d8899cbde8d8d068967980a34c0a3c): make it flexible, accepting request type as a constructor arguments. …

#217: support AUTHORIZATION and CHARGE for all payment types

---

service/src/main/java/com/commercetools/pspadapter/payone/mapping/BankTransferInAdvanceRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceChargeTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/BankTransferInAdvanceRequestFactoryTest.java

Just minor change: in case a customer creates a CTP transaction `CHARGE` (Payone _authorization_) we print a warning in the logs to notify them the transaction might be not supported by the service.
Despite Payone service accepts and handles this transaction type, BUT it is explicitly documented:
> 3.2.2 Initiating payment process (authorization)
> Prepayment Not supported by this request!
Also, as minor boy-scout change: renamed typo in class name <code>Bank<b>t</b>TransferInAdvanceRequestFactory</code> -> `BankTransferInAdvanceRequestFactory`

update warning in case of CHARGE(autorization) transaction for Prepayment (Vorkasse, BankTransferAdvanced) methods

---

README.md
service/src/main/java/com/commercetools/pspadapter/payone/config/PropertyProvider.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/banktransfer/BankTransferRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/AuthorizationRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/BaseRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/CaptureRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/util/ClearSecuredValuesSerializer.java
service/src/test/java/com/commercetools/pspadapter/payone/domain/payone/model/common/AuthorizationRequestTest.java

Customer related data shouldn't be logged. Therefore we need to provide a switch in the configuration which allows to anonymise/de-anonymise those data.
This switch implemented as an environment variable `HIDE_CUSTOMER_PERSONAL_DATA` which can be in 2 states: `"true"` OR `"false"`.
Default state is `"true"`. So if the environment variable is not provided then customer related data will be replaced by `<HIDDEN>` placeholder.

Add ClearSecuredValuesSerializer annotation to all sensitive bean fields

---

functionaltests/src/test/resources/specs/paymentmethods/paydirekt/Authorization.html
functionaltests/src/test/resources/specs/paymentmethods/paydirekt/ChargeImmediately.html
service/src/test/java/com/commercetools/util/HttpRequestUtilParallelTest.java
service/src/test/java/com/commercetools/util/HttpRequestUtilTest.java

In this pr, a JUnit test, with used 'httpbin' for testing requests, is fixed. The problem was,if the request "httpbin.org/post" was executes in "Http" context, this url was added to the response as "http://httpbin.org/post". This behavior has change, so that now the url is always added with as "https://httpbin.org/post" to the response.

Using testurl with https.

---

docs/Project-Lifecycle.md
functionaltests/src/test/java/specs/paymentmethods/sofortueberweisung/ChargeImmediatelyFixture.java
functionaltests/src/test/java/util/CustomWebDriver.java

In this pr, it was tried to "stabilize" the build process. For doing this the following was done:
1) Updating the webdriver to version
2) Executing the fixtures for sofortüberweisung sequentiell (instead of parellel).

Update chrome driver

---

service/src/main/java/com/commercetools/pspadapter/payone/IntegrationService.java
service/src/test/java/com/commercetools/pspadapter/payone/IntegrationServiceTest.java

The current implementation is causing some problems if ctp is failing with `504` or `500` status. So k8s restarting pod because of the platform issue, this leads some unexpected restarts.
with this PR, if the health endpoint is working, it will return HTTP ok (200) when it called by k8s  liveness/readiness probes. 
JIRA ticket: https://jira.commercetools.com/browse/CAR-2726

CAR-2726 remove ctp payment checks from health endpoint

---

service/src/main/java/com/commercetools/pspadapter/payone/PaymentHandler.java
service/src/main/java/com/commercetools/pspadapter/payone/ScheduledJob.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/PayonePostServiceImpl.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/PayoneRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/notification/NotificationProcessorBase.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/BaseDefaultTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BaseBankTransferInAdvanceTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/tenant/TenantLoggerUtil.java
service/src/test/java/com/commercetools/pspadapter/payone/PaymentHandlerTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/BaseTransaction_attemptExecutionTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceChargeTransaction_attemptExecutionTest.java

- Remove redundant logs
- Use tenant name as marker instead of logger name.
- Always add the exception, if there is, in the log stack trace.

Remove redundant logs

---

service/src/main/resources/logback.xml

don't shorten stack trace on error logs.

Don't shorten stack trace.

---

.dependabot/config.yml

Due to stuck Dependabot in pull requests, .dependabot/config.yml has been changed in order to avoid performing version update for some specific dependencies :
- mockito-core updates to 2.x.x in maximum.
- gradle-git-publish keeps the version unchanged.

Update dependabot config to avoid build failure

---

service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
service/src/test/java/com/commercetools/pspadapter/tenant/TenantFactoryTest.java

Apply QueueSphereClientDecorator for CTP client to limit concurrent request count. When number of request exceeds the limit threshold, incoming requests await in queue until number of processing request is less than the limit.

Add decorator

---

build.gradle
service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
service/src/main/java/com/commercetools/util/SphereClientConfigurationUtil.java
service/src/test/java/com/commercetools/util/SphereClientConfigurationUtilTest.java

RetrySphereClientDecorator is needed for recoverable errors on the payment service, as well as the request to CTP.
This is a newly created PR. The previous PR can be found here
#301 
It is because other fix for functional tests has been applied on master branch in these days. Featured branch has to be forked from master branch again to pass functional tests.

Add retry decorator v2

---

functionaltests/src/test/java/specs/paymentmethods/klarna/KlarnaFixture.java
functionaltests/src/test/java/specs/paymentmethods/klarna/KlarnaRequest.java
functionaltests/src/test/java/util/WebDriverPaydirekt.java

Ignored the Klarna payment method Integration tests due to a configuration problem in payone merchant account. As Klarna is only used by Coeur-de-lion and now this customer no longer with commercetools, we can safely ignore the tests for now as a temporary fix until we resolve the issue with payone.

ignore klarna ITs

---

service/src/main/java/com/commercetools/util/PayoneHttpClientUtil.java

Decreased the HTTP timeout value for payone HTTP client. New timeout is 5 seconds.

CAR-3312: reduce payone HTTP timeout from 8 sec to 5 sec

---

service/src/main/java/com/commercetools/pspadapter/payone/transaction/BaseDefaultTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/IdempotentTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/TransactionBaseExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BaseBankTransferInAdvanceTransactionExecutor.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/BaseTransaction_attemptExecutionTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/IdempotentTransactionExecutorTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceChargeTransaction_attemptExecutionTest.java

- We have already removed Quartz cronjobs within the library in the past. https://github.com/commercetools/commercetools-payone-integration/pull/226
- But we had mistakenly left some of the related logic in the payment request processing workflows. This pr have removed those logics.

remove retry logic which were related to quartz jobs

---

build.gradle
service/src/main/java/com/commercetools/pspadapter/payone/domain/ctp/TypeCacheLoader.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/BaseDefaultTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/IdempotentTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/TransactionBaseExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/common/AuthorizationTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/common/ChargeTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceAuthorizationTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BankTransferInAdvanceChargeTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/payone/transaction/paymentinadvance/BaseBankTransferInAdvanceTransactionExecutor.java
service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/BaseTransaction_attemptExecutionTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/IdempotentTransactionExecutorTest.java
service/src/test/java/com/commercetools/pspadapter/payone/transaction/common/AuthorizationTransactionExecutorTest.java
service/src/test/java/com/commercetools/pspadapter/tenant/TenantFactoryTest.java

NOTE: guava dependency is still active, as it will be removed in base-branch when this and https://github.com/commercetools/commercetools-payone-integration/pull/367 is merged into `remove_guava_dependency `.

Replace guavas caching library with caffeine

---

service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/AuthorizationRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/wallet/WalletAuthorizationRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/wallet/WalletPreauthorizationRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/MappingUtil.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/PayoneRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/WalletRequestFactory.java
service/src/test/java/com/commercetools/main/BasicPaymentRequestWorkflow.java
service/src/test/java/com/commercetools/main/BasicPaymentRequestWorkflowIT.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/BaseWalletRequestFactoryTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/MappingUtilTest.java
service/src/test/java/com/commercetools/pspadapter/tenant/TenantFactoryTest.java

- Add parameter `noShipping` to WalletPaymentTransfer.
- Set value 1 if Shipping Address is missing (any of the below values).
- PostalCode
- shippingCountry
- shipping_street
- city
related issue: https://github.com/commercetools/commercetools-payone-integration/issues/411

Set NoShipping to 1, When shipping address  is missing.

---

service/src/main/java/com/commercetools/pspadapter/payone/PaymentHandler.java

To fix integration test for ConcurrentModificationException, we need to revert the change in paymentHandler which made in previous [PR](https://github.com/commercetools/commercetools-payone-integration/pull/424/files)

Fix integration test for ConcurrentModificationException 

---

service/src/main/java/com/commercetools/util/PayoneHttpClientUtil.java

Currently it is logged that a request is retried even before it is checked that  a request can be retried.
In this pr the logging is changed, so that the retry is only be logged, when the request can be retried.

Only log if the request is really retried.

---

service/src/main/java/com/commercetools/pspadapter/payone/KlarnaStartSessionHandler.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/ctp/CustomTypeBuilder.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/PayoneRequest.java
service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/PayoneRequestWithCart.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/BankTransferInAdvanceRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/BankTransferWithoutIbanBicRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/CreditCardRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/CustomFieldKeys.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/MappingUtil.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/PayoneRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/WalletRequestFactory.java
service/src/main/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactory.java
service/src/test/java/com/commercetools/pspadapter/payone/KlarnaStartSessionHandlerTest.java
service/src/test/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactoryTest.java

In this pr the final modification was done, to make the Klarna payment working.
-Add required fields "workorderid" to payone-request.
- Remove shipping address from request for klarna payments

Adjustments of the klarna payment process
