commercetools/commercetools-payone-integration

- functionaltests/src/test/java/util/WebDriverSofortueberweisung.java
- functionaltests/src/test/java/util/constant/WebDriverCommon.java
@butenkor @ahalberkamp 
i've fixed the Sofortüberweisung tests: 
- The problem was in wrong button search approach, so after the page design change Selenium web-driver found another button (hidden menu button) instead of _submit_ button.
- also added failsafe check that exactly one submit button exists on the page (see `findSubmitButton()` method)
> #151: fixed Sofortüberweisung selenium tests

- service/src/main/java/com/commercetools/pspadapter/payone/util/MoneyUtil.java
- service/src/test/java/com/commercetools/pspadapter/payone/util/MoneyUtilTest.java
Just minor change: function `getTotalDiscountedPricePerQuantity()` is extended to have additional `getTotalDiscountedPriceMonetaryPerQuantity()`, which returns `MonetaryAmount`, instead of integer cents.
> Minor money util update

- README.md
- docs/Shop-Integration-Guide.md
@butenkor @floriansattler @lojzatran 
Pls review the _Payment amount validation_ notes for shop developers. We need to publish them an reference every time for the shop developers.
This document will be extended with more notes and cases in the future.
> #168: add payment validation front-end documentation

- build.gradle
- functionaltests/src/test/java/specs/response/HealthResponseFixture.java
- service/src/main/java/com/commercetools/pspadapter/payone/IntegrationService.java
- service/src/main/java/com/commercetools/pspadapter/payone/config/PropertyProvider.java
- service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
- service/src/test/java/com/commercetools/pspadapter/payone/IntegrationServiceTest.java
In the pr a  liveness probe probe is implemented, which  requests the payment endpoint of the CT platform and check, if request was  successful. In this case the liveness probe returns the https status code "200". Otherwise it returns the http status code "503"
Related task:https://github.com/commercetools/commercetools-payone-integration/issues/227
> 227:Add liveness probe.

- functionaltests/src/test/resources/specs/initialPendingMigration/InitialPendingMigration.html
- functionaltests/src/test/resources/specs/multitenancy/creditcard/ChargeImmediatelyWithout3ds2.html
- functionaltests/src/test/resources/specs/paymentmethods/creditcard/ChargeImmediatelyWith3ds.html
- functionaltests/src/test/resources/specs/paymentmethods/creditcard/ChargeImmediatelyWithout3ds.html
- functionaltests/src/test/resources/specs/scheduler/ScheduledJobShort.html
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/AuthorizationRequestWithCart.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/ExtendedAuthorizationRequest.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/creditcard/CreditCardAuthorizationRequest.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/creditcard/CreditCardPreauthorizationRequest.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/klarna/KlarnaAuthorizationRequest.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/klarna/KlarnaPreauthorizationRequest.java
- service/src/main/java/com/commercetools/pspadapter/payone/mapping/CreditCardRequestFactory.java
- service/src/main/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactory.java
- service/src/test/java/com/commercetools/pspadapter/payone/mapping/CreditCardRequestFactoryTest.java
- service/src/test/java/com/commercetools/pspadapter/payone/mapping/MappingUtilTest.java
- service/src/test/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactoryTest.java
In this PR cart-data is added to the creditcard pre- and authorization request to improve the customer experience.
This was recommended by payone, please check: https://docs.payone.com/display/public/PLATFORM/Special+remarks+-+3-D+Secure
Jira: https://jira.commercetools.com/browse/CAR-2670
> Car 2670: add cart to cc

- service/src/main/java/com/commercetools/pspadapter/payone/PaymentHandler.java
In this pr an exception was added to the error-log to simplify debugging
> Log exception, when payment cannot be found.

- .travis.yml
- functionaltests/src/test/java/util/CustomWebDriver.java
- functionaltests/src/test/java/util/WebDriverPaydirekt.java
- functionaltests/src/test/resources/specs/response/HealthResponse.html
In this pr, the test for paydirekt was fixed. The fix was required for the selenium test, because the UI of paydirekt was changed.
> Fix paydirekt test

- .dependabot/config.yml
Automerge dependabot dependencies.
> Automerge dependabot dependencies.

- functionaltests/src/test/java/util/CustomWebDriver.java
In this pr I have updated to chrome driver to version 84
> CAR-2932:Update chrome driver to version 85

- build.gradle
- docs/Project-Lifecycle.md
- functionaltests/src/test/java/util/CustomWebDriver.java
> introduced chromedriver manager library

- service/src/main/java/com/commercetools/pspadapter/payone/domain/ctp/paymentmethods/PaymentMethod.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/ClearingType.java
- service/src/main/java/com/commercetools/pspadapter/payone/mapping/BankTransferWithoutIbanBicRequestFactory.java
- service/src/main/java/com/commercetools/pspadapter/tenant/TenantFactory.java
- service/src/test/java/com/commercetools/pspadapter/payone/mapping/BankTransferWithoutIbanBicRequestFactoryTest.java
- service/src/test/java/com/commercetools/pspadapter/tenant/TenantFactoryTest.java
- service/src/test/java/util/PaymentTestHelper.java
- service/src/test/resources/dummyPaymentOneAuthPending20Euro_BCT.json
Fixes: #307 
I also tested it manually the process and it seems to work. I received a success notification for the payment. See `paymentId="5e90dd5a-ab06-4b53-991f-f42ffcac5453"` in a project `ct-payone-integration-ci`
> #307 add bancontact

- service/src/main/java/com/commercetools/pspadapter/payone/PaymentHandler.java
- service/src/test/java/com/commercetools/pspadapter/payone/PaymentHandlerTest.java
- Fixed unnecessary iterations on successful payment handling
- Reduce retry count from 20 to 5
- Add variable delay for retrying mechanism
> 312: remove unnecessary iterations on successful payment processing

- service/src/main/java/com/commercetools/util/HttpRequestUtil.java
Reduce the HTTP **keep-Alive** time to minimize the idle time for a HTTP connection
> Reduce http keep alive

- service/src/main/java/com/commercetools/util/SphereClientConfigurationUtil.java
- service/src/test/java/com/commercetools/util/SphereClientConfigurationUtilTest.java
Add retry predicate so that retry mechanism can be triggered when HTTP exception occurs during sending request to CTP.
> Add retry predicate and unit test

- README.md
- functionaltests/src/test/java/util/CustomWebDriver.java
In this pr the payment-methods, which were provided by payone, were  documented.
> document used paymentmethods.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fix the vulnerable dependencies
https://app.snyk.io/org/butenkor/project/d83de7b9-abdd-4c84-baac-e40443956822
Some dependencies are direct dependencies, while most of them are transitive dependencies underlying inside jvm-sdk.
Based on official support, vulnerability report is more accurate in Snyk CLI
https://support.snyk.io/hc/en-us/articles/360002615737-Snyk-CLI-shows-no-vulnerabilities-but-Snyk-UI-does
Therefore, to verify the security fix, it is recommended to test the vulnerability in CLI :
1. Download and install Snyk CLI by Homebrew 
https://support.snyk.io/hc/en-us/articles/360003812538-Install-the-Snyk-CLI#UUID-876089c6-d195-a81e-4c7a-21354f788306
2. Checkout the source from branch 'fix-securit-issue''
3. In command prompt, input 'snyk monitor --all-projects'
> Fix security issue

- build.gradle
- docs/Project-Lifecycle.md
- service/src/test/java/com/commercetools/main/BasicPaymentRequestWorkflow.java
- service/src/test/java/util/PaymentRequestHelperUtil.java
- service/src/test/java/util/PropertiesHelperUtil.java
- service/src/test/resources/test.internal.properties.skeleton
- Added test setup for payment transactions workflow.
- Test to Verify credit card payone payment transaction.
> Test to simulate a checkout workflow.

- README.md
In this pr the link to the loglevel documentation was corrected.
> Update link to loglevel documentation.

- build.gradle
- service/src/main/java/com/commercetools/pspadapter/payone/domain/ctp/CustomTypeBuilder.java
- service/src/main/java/com/commercetools/pspadapter/payone/mapping/CustomFieldKeys.java
Extend Klarna custom type with the following fields:
```
startSessionResponse (text)
clientToken (text)
authorizationToken (text)
redirectUrl (text)
errorUrl (text)
successUrl (text)
backUrl (text)
```
JIRA: https://jira.commercetools.com/browse/CAR-3769
> Create klarna custom type on startup

- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/PayoneRequestWithCart.java
- service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/common/StartSessionRequestWithCart.java
- service/src/main/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactory.java
- service/src/test/java/com/commercetools/pspadapter/payone/mapping/klarna/KlarnaRequestFactoryTest.java
- service/src/test/resources/com/commercetools/pspadapter/payone/mapping/klarna/dummyPaymentForKlarnaCartWithoutDiscounts_KIV.json
- service/src/test/resources/com/commercetools/pspadapter/payone/mapping/klarna/dummyPaymentForKlarnaCart_KIV.json
In this pr the authorisation-token was added to the klarna- authorisationrequest.
> Klarna authorisationtoken
